/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AppRouteImport } from './routes/_app';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AppTeamRouteImport } from './routes/_app/team';
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions';
import { Route as AppSettingsRouteImport } from './routes/_app/settings';
import { Route as AppSavingsRouteImport } from './routes/_app/savings';
import { Route as AppRenewalsRouteImport } from './routes/_app/renewals';
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations';
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard';
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics';

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any);
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any);
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any);
const AppRenewalsRoute = AppRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AppRoute,
} as any);
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any);
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/analytics': typeof AppAnalyticsRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/integrations': typeof AppIntegrationsRoute;
  '/renewals': typeof AppRenewalsRoute;
  '/savings': typeof AppSavingsRoute;
  '/settings': typeof AppSettingsRoute;
  '/subscriptions': typeof AppSubscriptionsRoute;
  '/team': typeof AppTeamRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/analytics': typeof AppAnalyticsRoute;
  '/dashboard': typeof AppDashboardRoute;
  '/integrations': typeof AppIntegrationsRoute;
  '/renewals': typeof AppRenewalsRoute;
  '/savings': typeof AppSavingsRoute;
  '/settings': typeof AppSettingsRoute;
  '/subscriptions': typeof AppSubscriptionsRoute;
  '/team': typeof AppTeamRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_app': typeof AppRouteWithChildren;
  '/_app/analytics': typeof AppAnalyticsRoute;
  '/_app/dashboard': typeof AppDashboardRoute;
  '/_app/integrations': typeof AppIntegrationsRoute;
  '/_app/renewals': typeof AppRenewalsRoute;
  '/_app/savings': typeof AppSavingsRoute;
  '/_app/settings': typeof AppSettingsRoute;
  '/_app/subscriptions': typeof AppSubscriptionsRoute;
  '/_app/team': typeof AppTeamRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/integrations'
    | '/renewals'
    | '/savings'
    | '/settings'
    | '/subscriptions'
    | '/team';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/integrations'
    | '/renewals'
    | '/savings'
    | '/settings'
    | '/subscriptions'
    | '/team';
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/integrations'
    | '/_app/renewals'
    | '/_app/savings'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/team';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/team': {
      id: '/_app/team';
      path: '/team';
      fullPath: '/team';
      preLoaderRoute: typeof AppTeamRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/subscriptions': {
      id: '/_app/subscriptions';
      path: '/subscriptions';
      fullPath: '/subscriptions';
      preLoaderRoute: typeof AppSubscriptionsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/settings': {
      id: '/_app/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/savings': {
      id: '/_app/savings';
      path: '/savings';
      fullPath: '/savings';
      preLoaderRoute: typeof AppSavingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/renewals': {
      id: '/_app/renewals';
      path: '/renewals';
      fullPath: '/renewals';
      preLoaderRoute: typeof AppRenewalsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/integrations': {
      id: '/_app/integrations';
      path: '/integrations';
      fullPath: '/integrations';
      preLoaderRoute: typeof AppIntegrationsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/dashboard': {
      id: '/_app/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/analytics': {
      id: '/_app/analytics';
      path: '/analytics';
      fullPath: '/analytics';
      preLoaderRoute: typeof AppAnalyticsRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute;
  AppDashboardRoute: typeof AppDashboardRoute;
  AppIntegrationsRoute: typeof AppIntegrationsRoute;
  AppRenewalsRoute: typeof AppRenewalsRoute;
  AppSavingsRoute: typeof AppSavingsRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute;
  AppTeamRoute: typeof AppTeamRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppRenewalsRoute: AppRenewalsRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTeamRoute: AppTeamRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
